import type { Metadata } from 'next';
import './globals.css';
import { Header } from './_components/_globals/Header/Header';
import { Footer } from './_components/_globals/Footer/Footer';


export const metadata: Metadata = {
	title: 'Woodly',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='ro'>

			<body>
				<Header />
				<main>{children}</main>
				<Footer />
			</body>
		</html>
	);
}
